matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services: docker
    - os: osx
      osx_image: xcode8.3.2

#services:
#  - docker

env:
  global:
  - REPORT_EXIT_STATUS=1
  - ACCEPT_EULA=Y
  - PHPSQLDIR=/REPO/msphpsql-dev
  - TEST_PHP_SQL_SERVER=sql
  - SQLSRV_DBNAME=msphpsql_sqlsrv
  - PDOSQLSRV_DBNAME=msphpsql_pdosqlsrv  

before_install:
  #- docker pull microsoft/mssql-server-linux
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      brew update 
      brew tap homebrew/dupes
      brew tap homebrew/versions
      brew tap homebrew/homebrew-php
      brew install php70
      brew tap microsoft/homebrew-mssql-release
      brew update
      brew install mssql-tools
      brew cask install docker
      sudo /Volumes/Docker/Docker.app/Contents/MacOS/Docker
      docker ps -a
      docker --version
      docker run hello-world
      docker pull microsoft/mssql-server-linux
    else
      docker pull microsoft/mssql-server-linux
    fi
 
install:
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      docker build --build-arg PHPSQLDIR=$PHPSQLDIR -t msphpsql-dev -f Dockerfile-msphpsql .
      docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password12@' -p 1433:1433 --name=$TEST_PHP_SQL_SERVER -d microsoft/mssql-server-linux
    fi

script: 
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      docker run -e TRAVIS_JOB_ID -t -d -w $PHPSQLDIR --link $TEST_PHP_SQL_SERVER --name=client msphpsql-dev
      docker ps -a 
      docker exec client python ./test/setup/setup_dbs.py -dbname $SQLSRV_DBNAME
      docker exec client python ./test/setup/setup_dbs.py -dbname $PDOSQLSRV_DBNAME
      docker exec client php ./source/pdo_sqlsrv/run-tests.php ./test/pdo_sqlsrv/*.phpt
      docker exec client php ./source/sqlsrv/run-tests.php ./test/sqlsrv/*.phpt
      docker exec client bash -c 'for f in ./test/sqlsrv/*.diff; do ls $f 2>/dev/null; cat $f 2>/dev/null; done || true'
      docker exec client bash -c 'for f in ./test/sqlsrv/*.out; do ls $f 2>/dev/null; cat $f 2>/dev/null; done || true'
      docker exec client bash -c 'for f in ./test/pdo_sqlsrv/*.diff; do ls $f 2>/dev/null; cat $f 2>/dev/null; done || true' 
      docker exec client bash -c 'for f in ./test/pdo_sqlsrv/*.out; do ls $f 2>/dev/null; cat $f 2>/dev/null; done || true' 
      docker exec client python ./test/setup/cleanup_dbs.py -dbname $SQLSRV_DBNAME
      docker exec client python ./test/setup/cleanup_dbs.py -dbname $PDOSQLSRV_DBNAME
      docker exec client coveralls -e ./source/shared/ --gcov-options '\-lp'
      docker stop client
      docker ps -a 
    else
      clang --version
      export BUILDDIR=$PWD/source
      echo $BUILDDIR
      cd $BUILDDIR
      chmod a+x packagize.sh
      /bin/bash packagize.sh
      cd $BUILDDIR/sqlsrv
      phpize
      ./configure 
      make
      cd $BUILDDIR/pdo_sqlsrv
      phpize
      ./configure 
      make
      php --ini | grep "Loaded Configuration"
    fi

notifications:
  email: false
